# -*- coding: utf-8 -*-
"""Projeto2_GAV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UoyzbbzPBm4CdHVcKQkrDWbvhHuxSBPQ
"""

import numpy as np
import plotly.graph_objects as go


# Função para criar um vetor 3D com linha + cone
def vetor(P, Q, nome="vetor", cor="black", tamanho_cone=0.17):
    P = np.array(P)
    Q = np.array(Q)
    direcao = Q - P
    norma = np.linalg.norm(direcao)
    if norma == 0:
        direcao = np.array([0, 0, 0])
    else:
        direcao = direcao / norma
    cone = go.Cone(
        name=nome,
        x=[Q[0]], y=[Q[1]], z=[Q[2]],
        u=[direcao[0]], v=[direcao[1]], w=[direcao[2]],
        colorscale=[[0, cor], [1, cor]],
        sizemode="absolute",
        sizeref=tamanho_cone,
        showscale=False,
        anchor="tip" # Ponta termina logo no final
    )
    linha = go.Scatter3d(
        name=nome,
        x=[P[0], Q[0]], y=[P[1], Q[1]], z=[P[2], Q[2]],
        mode="lines",
        line=dict(width=5, color=cor)
    )
    return [linha, cone]

# Vetores
O = np.array([0, 0, 0])           # origem
u = np.array([1, 2, 0])           # base
v = np.array([2, 1, 3])           # vetor a projetar

# Projeção de v sobre u
proj_coef = np.dot(v, u) / np.dot(u, u)
proj = proj_coef * u

# Criar figuras
fig = go.Figure()

# Vetor u
fig.add_traces(vetor(O, u, nome="u", cor="blue"))

# Vetor v
fig.add_traces(vetor(O, v, nome="v", cor="green"))

# Projeção de v sobre u
fig.add_traces(vetor(O, proj, nome="proj_u(v)", cor="red"))

# Vetor perpendicular (v - proj)
fig.add_traces(vetor(proj, v, nome="v - proj", cor="orange"))

# Layout
fig.update_layout(scene=dict(aspectmode='cube'), title="Projeção de Vetor")
fig.show()

import numpy as np
import plotly.graph_objects as go

# Função para criar um vetor 3D com linha + cone
def vetor(P, Q, nome="vetor", cor="black", tamanho_cone=0.5):
    P = np.array(P)
    Q = np.array(Q)
    direcao = Q - P
    norma = np.linalg.norm(direcao)
    if norma == 0:
        direcao = np.array([0, 0, 0])
    else:
        direcao = direcao / norma
    cone = go.Cone(
        name=nome,
        x=[Q[0]], y=[Q[1]], z=[Q[2]],
        u=[direcao[0]], v=[direcao[1]], w=[direcao[2]],
        colorscale=[[0, cor], [1, cor]],
        sizemode="absolute",
        sizeref=tamanho_cone,
        showscale=False,
        anchor="tip" # Ponta termina logo no final
    )
    linha = go.Scatter3d(
        name=nome,
        x=[P[0], Q[0]], y=[P[1], Q[1]], z=[P[2], Q[2]],
        mode="lines",
        line=dict(width=5, color=cor)
    )
    return [linha, cone]

# Vetores
O = np.array([0, 0, 0])           # origem
u = np.array([1, 2, 0])           # vetor 1
v = np.array([2, 1, 3])           # vetor 2


# Produto vetorial
prod_vetorial = np.cross(u, v)
norma = np.linalg.norm(prod_vetorial)
prod_vetorial = (prod_vetorial / norma) * 3 # diminuir o tamanho do vetor, por ex: * 0.5

# Criar figuras
fig = go.Figure()

# Vetor u
fig.add_traces(vetor(O, u, nome="u", cor="blue"))

# Vetor v
fig.add_traces(vetor(O, v, nome="v", cor="green"))

# Produto vetorial (perpendicular aos dois)
fig.add_traces(vetor(O, prod_vetorial, nome="produto vetorial", cor="black"))

# Layout
fig.update_layout(scene=dict(aspectmode='cube'), title="Produto Vetorial de u e v")

fig.show()