# -*- coding: utf-8 -*-
"""TrabalhoGAVCônicas_Quadricas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AHirTMkVKMjVETkwlBd7k44jxYd5uClF
"""

import numpy as np

"""#**Elipsóide**"""

import plotly.graph_objects as go
import numpy as np

X, Y, Z = np.mgrid[-5:5:40j, -5:5:40j, -5:5:40j]

values = X * X * 0.5 + Y * Y + Z * Z * 2

fig = go.Figure(data=go.Isosurface(
x=X.flatten(),
y=Y.flatten(),
z=Z.flatten(),
value=values.flatten(),
isomin=10,
isomax=40,
caps=dict(x_show=False, y_show=False, z_show=False),
colorscale=[[0, 'red'], [1, 'pink']]
))
fig.show()

"""# **Parabolóide Hiperbólico**"""

import plotly.graph_objects as go
import numpy as np

X, Y, Z = np.mgrid[-5:5:40j, -5:5:40j, -5:5:40j]

values = X * X * 0.5 - Y * Y * 0.5 - Z * 2.5

fig = go.Figure(data=go.Isosurface(
    x=X.flatten(),
    y=Y.flatten(),
    z=Z.flatten(),
    value=values.flatten(),
    isomin=0.1,
    isomax=0.1,
    caps=dict(x_show=False, y_show=False, z_show=False),
    colorscale=[[0, 'red'], [1, 'blue']]
))
fig.show()

"""#**Hiperbolóide de Uma Folha**"""

import plotly.graph_objects as go
import numpy as np

X, Y, Z = np.mgrid[-5:5:40j, -5:5:40j, -5:5:40j]

values = Z**2 - X**2 - Y**2

fig = go.Figure(data=go.Isosurface(
    x=X.flatten(),
    y=Y.flatten(),
    z=Z.flatten(),
    value=values.flatten(),
    isomin=0,
    isomax=1,
    caps=dict(x_show=False, y_show=False, z_show=False),
    colorscale='magma'
))

fig.show()

"""#**Hipérbole de Duas Folhas**"""

import plotly.graph_objects as go
import numpy as np

X, Y, Z = np.mgrid[-5:5:40j, -5:5:40j, -5:5:40j]

values = X * X * 2 + Y * Y * 3 - Z * Z * 2

fig = go.Figure(data=go.Isosurface(
    x=X.flatten(),
    y=Y.flatten(),
    z=Z.flatten(),
    value=values.flatten(),
    isomin=1,
    isomax=1,
    caps=dict(x_show=False, y_show=False, z_show=False),
    colorscale='magma'
))

fig.show()

"""#**Parabolóide Eliptico**"""

import plotly.graph_objects as go
import numpy as np

X, Y, Z = np.mgrid[-5:5:40j, -5:5:40j, -5:5:40j]

values = X * X * 2 + Y * Y * 3 - Z * 2

fig = go.Figure(data=go.Isosurface(
    x=X.flatten(),
    y=Y.flatten(),
    z=Z.flatten(),
    value=values.flatten(),
    isomin=1,
    isomax=1,
    caps=dict(x_show=False, y_show=False, z_show=False),
    colorscale='magma'
))

fig.show()

"""#**Cone**"""

import plotly.graph_objects as go
import numpy as np

X, Y, Z = np.mgrid[-5:5:40j, -5:5:40j, -5:5:40j]

values = X * X * 2 + Y * Y * 2 - Z * Z * 2

fig = go.Figure(data=go.Isosurface(
    x=X.flatten(),
    y=Y.flatten(),
    z=Z.flatten(),
    value=values.flatten(),
    isomin=0.04, # o ideal seria colocar 0.0, porém coloquei 0.04 para que os cones se juntassem.
    isomax=0.04,
    caps=dict(x_show=False, y_show=False, z_show=False),
    colorscale='magma'
))

fig.show()

"""#**Cilindros**"""

import plotly.graph_objects as go
import numpy as np

X, Y, Z = np.mgrid[-5:5:40j, -5:5:40j, -5:5:40j]

# a equação do cilindro é (x^2 + y^2 = r^2)
values = X * X + Y * Y

fig = go.Figure(data=go.Isosurface(
    x=X.flatten(),
    y=Y.flatten(),
    z=Z.flatten(),
    value=values.flatten(),
    isomin=5,  # Aqui adaptamos o raio do cilindro representado. Nesse caso optei por 5
    isomax=5,
    caps=dict(x_show=False, y_show=False, z_show=False),
    colorscale='magma'
))

fig.show()

"""#**Esfera**"""

import plotly.graph_objects as go
import numpy as np

X, Y, Z = np.mgrid[-5:5:40j, -5:5:40j, -5:5:40j]

# Aqui eu achei mais conveniente utilizar essa equação definindo os pontos do espaço, porém
# poderia utilizar a equação para partir da origem:
# x² + y² + z² = r².
values = (X - 1) * (X - 1) + (Y - 1) * (Y - 1) + (Z - 1) * (Z - 1)

fig = go.Figure(data=go.Isosurface(
    x=X.flatten(),
    y=Y.flatten(),
    z=Z.flatten(),
    value=values.flatten(),
    isomin=5,  # Aqui adaptamos o raio da esfera. Nesse caso optei por 5
    isomax=5,
    caps=dict(x_show=False, y_show=False, z_show=False),
    colorscale='magma'
))

fig.show()

"""#**Hipérbole**"""

delta = 0.025
xrange = np.arange(-2, 2, delta)
yrange = np.arange(-2, 2, delta)
X, Y = np.meshgrid(xrange,yrange)
F = X**2 - Y**2


fig = go.Figure(data =
    go.Contour(
        z = F,
        x = xrange,
        y = yrange,
        contours_coloring='lines',
        line_width = 2,
        contours=dict(
            start=1,
            end=1,
            size=2,
        ),
    ),
        layout=go.Layout(
        title='Hipérbole',
    ))
fig.show()

"""#**Elipse**"""

import plotly.graph_objects as go
import numpy as np

delta = 0.025
xrange = np.arange(-3, 3, delta)
yrange = np.arange(-3, 3, delta)
X, Y = np.meshgrid(xrange,yrange)

a = 1.5
b = 2.5
F = (X/a)**2 + (Y/b)**2


fig = go.Figure(data =
    go.Contour(
        z = F,
        x = xrange,
        y = yrange,
        contours_coloring='lines',
        line_width = 2,
        contours=dict(
            start=1,
            end=1,
        ),
    ),
    layout=go.Layout(
        title='Elipse',
    ))
fig.show()

"""#**Parábola**"""

delta = 0.025
xrange = np.arange(-2, 2, delta)
yrange = np.arange(-2, 2, delta)
X, Y = np.meshgrid(xrange,yrange)
F = X**2 + Y


fig = go.Figure(data =
    go.Contour(
        z = F,
        x = xrange,
        y = yrange,
        contours_coloring='lines',
        line_width = 2,
        contours=dict(
            start=1,
            end=1,
        ),
    ),
        layout=go.Layout(
        title='Parábola',
    ))
fig.show()

"""#**Circunferência**"""

delta = 0.025
xrange = np.arange(-2, 2, delta)
yrange = np.arange(-2, 2, delta)
X, Y = np.meshgrid(xrange,yrange)
F = X * X + Y * Y


fig = go.Figure(data =
    go.Contour(
        z = F,
        x = xrange,
        y = yrange,
        contours_coloring='lines',
        line_width = 2,
        contours=dict(
            start=1,
            end=1,
        ),
    ),
    layout=go.Layout(
        title='Circunferência',
        yaxis = dict(scaleanchor="x") # para ajustar e remover as distorções
    )
)
fig.show()